recipes:
    global:
        - applications::create_var_chef_cache
    mac_os_x:
        - homebrewalt::default
        - osxdefaults::enable_remote_desktop
        - osxdefaults::enable_remote_login
        - osxdefaults::check_for_software_updates_daily
        - osxdefaults::enable_subpixel_font_rendering_on_non-apple_lcds
        - osxdefaults::save_screenshots_in_png_format
        - osxdefaults::finder_small_sidebar_icon_size
        - osxdefaults::automatically_quit_printer_app_once_the_print_jobs_complete
        - osxdefaults::avoid_creating_ds_store_files_on_network_volumes
        - osxdefaults::dock_make_dock_icons_of_hidden_applications_translucent
        - osxdefaults::tap_to_click
        - osxdefaults::finder_search_the_current_folder_by_default

attributes:
    homebrewalt:
        apps:
            - git
            - readline
            - bash
        cask_apps:
            - flash-player

