groups:
    - pebble
    - pebble-dev

recipes:
    global:
        - dotfiles::gitconfig

attributes:
    homebrewalt:
        taps:
            - franc0is/pebble-fw
        apps:
            - arcanist
            - git-extras
            - wget
            - cppcheck
            - doxygen
            - freetype
            - llvm
            - libgit2
            - grep
            - pypy
            - ragel
            - gettext
            - libftdi
            - libusb-compat
            - autoconf
            - automake 
            - libtool
            - libftdi0
            - pkg-config
            - pebble-openocd
            - pebble-qemu
            - llvm
        cask_apps:
            - sourcetree
